FROM apache/airflow:2.10.4

USER root
RUN apt-get update && apt-get install -y gcc g++ && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir \
    boto3==1.34.69 \
    beautifulsoup4==4.12.3 \
    lxml==5.2.1 \
    sentence-transformers==3.0.1 \
    scikit-learn==1.5.0 \
    spacy==3.8.2 \
    structlog==24.1.0 \
    requests==2.32.3 \
    snowflake-connector-python==3.7.0 \
    python-dotenv==1.0.1

RUN python -m spacy download en_core_web_sm
