-- Run once if HTS_CODES was created with older VARCHAR(12) hts_code columns.
USE DATABASE TARIFFIQ;
USE SCHEMA RAW;

ALTER TABLE HTS_CODES ALTER COLUMN hts_id SET DATA TYPE VARCHAR(32);
ALTER TABLE HTS_CODES ALTER COLUMN hts_code SET DATA TYPE VARCHAR(32);

ALTER TABLE NOTICE_HTS_CODES ALTER COLUMN hts_code SET DATA TYPE VARCHAR(32);
ALTER TABLE PRODUCT_ALIASES ALTER COLUMN hts_code SET DATA TYPE VARCHAR(32);
ALTER TABLE HITL_RECORDS ALTER COLUMN classifier_hts SET DATA TYPE VARCHAR(32);
