-- Add columns for Federal Register pipeline redesign
USE DATABASE TARIFFIQ;
USE SCHEMA RAW;

ALTER TABLE FEDERAL_REGISTER_NOTICES ADD COLUMN IF NOT EXISTS s3_key VARCHAR(300);
ALTER TABLE FEDERAL_REGISTER_NOTICES ADD COLUMN IF NOT EXISTS content_hash VARCHAR(64);
ALTER TABLE FEDERAL_REGISTER_NOTICES ADD COLUMN IF NOT EXISTS processing_status VARCHAR(20) DEFAULT 'pending';
ALTER TABLE FEDERAL_REGISTER_NOTICES ADD COLUMN IF NOT EXISTS processing_error TEXT;
ALTER TABLE FEDERAL_REGISTER_NOTICES ADD COLUMN IF NOT EXISTS word_count INTEGER;
