USE DATABASE TARIFFIQ;
USE SCHEMA RAW;

ALTER TABLE FEDERAL_REGISTER_NOTICES
    ALTER COLUMN processing_status SET DATA TYPE VARCHAR(50);

ALTER TABLE NOTICE_HTS_CODES
    ALTER COLUMN match_status SET DATA TYPE VARCHAR(50);
